version: '3'

services:
  dev-database:
    image: postgres:latest
    container_name: personal-note-api-dev-database
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal-note-api
    networks:
      - nestjs-network

  test-database:
    image: postgres:latest
    container_name: personal-note-api-test-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal-note-api
    networks:
      - nestjs-network

networks:
  nestjs-network:
