version: '3'

services:
  database:
    image: postgres:latest
    container_name: personal-note-api-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal-note-api
    networks:
      - nestjs-network

networks:
  nestjs-network:
